spring.application.name=ItemsService

server.port=9092

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/microservice
spring.datasource.username=postgres
spring.datasource.password=gaurav@123
spring.jpa.hibernate.ddl-auto=update
