spring.application.name=_01_Spring_Jpa_Implementation

spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix= .jsp

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username= postgres
spring.datasource.password= gaurav@123
spring.jpa.hibernate.ddl-auto=update